<!DOCTYPE html>
 
<head>
 
	<title>pWidget</title>
 
	<!-- JavaScript -->
	<script type="text/javascript">
		// Put code here or set the src attribute
	</script>
 
	<!-- CSS -->
	<style type="text/css">
	<!--
 
		body { background-color: white; margin: 0; padding: 0; font-family: Arial, Verdana, sans-serif; font-size: 12px; }
		p { margin-bottom: 10px; }
		.estimate { color: silver; font-weight: bold; float: left; margin-right: 5px; width: 15px; }
		.name { float: left; width: 80%; }
		.strike { text-decoration: line-through; }
		.line { border-top: 1px solid white; border-bottom: 1px solid #dddddd; padding-top: 5px; padding-bottom: 5px; background-color: #f4f4f4; height: auto; }
		.arrow { color: grey; float: left; width: 10%; text-align: center; }
		.priority { float: left; width: 10%; }
		.done { background-color: #daebcf; border-top: 1px solid #eefce2; border-bottom: 1px solid #c3d5b4; }
		.started { background-color: #f3f3d1; }
		.release { background-color: #407aa5; border-top: 1px solid #5982a7; border-bottom: 1px solid #306494; }
		.release a { color: white !important; }
		.release .arrow { color: silver; }
		.labels { color: green; font-size: 0.85em; font-weight: bold; }
		.owned_by { color: darkblue; }
		a { color: black; text-decoration: none; }
		.save { background-color: silver; color: grey; border-top: 1px solid #ececec; border-bottom: 1px solid #888888; }
		.header { background-color: #333333; color: white; font-weight: bold; padding: .75em 0 .75em 0; border: 0; }

	-->
	</style>
 
</head>
 
<body>

	<? if ($title != 'n'): ?>
	<div class="line header">
		<p style="text-align: center; margin: 0;"><? echo $title; ?></p>
	</div> 
	<? endif; ?>
	<? foreach($stories as $s): ?>
		<div class="line <? if ($s['story_type'] == 'release'): ?>release<? elseif (in_array($s['current_state'], $done)): ?>done<? endif; ?> <? if ($s['current_state'] == 'started'): ?> started<? endif; ?>">
			<div class="arrow">
				>
			</div>
			<? if ($s['priority'] != ''): ?>
			<div class="priority">
				<? echo $s['priority']; ?>&nbsp;
			</div>
			<? endif; ?>
			<div class="estimate">
				<? if ($s['estimate'] >= 0): ?>
					<? echo $s['estimate']; ?>&nbsp;
				<? else: ?>
					&nbsp;
				<? endif; ?>
			</div>
			<div class="name<? if (in_array($s['current_state'], array('finished', 'delivered', 'accepted'))): ?> strike<? endif; ?>">
				<span class="labels"><?echo $s['labels']; ?></span> 
				<a href="https://www.pivotaltracker.com/story/show/<? echo $s['id']; ?>" target="<? echo $target; ?>">
					<? echo $s['name']; ?> 
				</a>
				<? if ($s['owned_by']): ?>(<span class="owned_by"><? echo $s['owned_by']; ?>)</span><? endif; ?>
			</div>
			<div style="clear: both;"></div>
		</div>
	<? endforeach; ?>
	<? if($_GET['load'] == ''): ?>
	<div class="line save">
		<p style="text-align: center; margin: 0;"><a href="?<? echo $_SERVER['QUERY_STRING']; ?>&save=y">Save and Secure this Widget</a></p>
	</div>
	<? endif; ?>
 
</body>
 
</html>
