<!DOCTYPE html>
 
<head>
 
	<title>pWidget</title>
	
	<? if ($refresh): ?><meta http-equiv="refresh" content="<? echo($refresh); ?>"><? endif; ?>
 
	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="<? echo($style); ?>.css">
	<style type="text/css">
 
 		<? if ($cols == 4): ?>
		.name { 
			width: 70%;
		}
		<? endif; ?>

	</style>

	<!-- Google Analytics -->
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-27761814-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	  
	</script>
	<!-- End Google Analytics -->

</head>
 
<body>

	<? if ($title != 'n'): ?>
	<div class="line header">
		<p style="text-align: center; margin: 0;"><? echo $title; ?></p>
	</div> 
	<? endif; ?>
	<? foreach($stories as $s): ?>
		<div class="line <? if ($s['story_type'] == 'release'): ?>release<? elseif (in_array($s['current_state'], $done)): ?>done<? endif; ?> <? if ($s['current_state'] == 'started'): ?> started<? endif; ?>">
			<div class="arrow">
				>
			</div>
			<? if ($s['priority'] != ''): ?>
			<div class="priority">
				<? echo $s['priority']; ?>&nbsp;
			</div>
			<? endif; ?>
			<div class="estimate">
				<? if ($s['estimate'] >= 0): ?>
					<? echo $s['estimate']; ?>&nbsp;
				<? else: ?>
					&nbsp;
				<? endif; ?>
			</div>
			<div class="name<? if (in_array($s['current_state'], array('finished', 'delivered', 'accepted'))): ?> strike<? endif; ?>">
				<span class="labels"><?echo $s['labels']; ?></span> 
				<a href="https://www.pivotaltracker.com/story/show/<? echo $s['id']; ?>" target="<? echo $target; ?>">
					<? echo $s['name']; ?> 
				</a>
				<? if ($s['owned_by']): ?>(<span class="owned_by"><? echo $s['owned_by']; ?>)</span><? endif; ?>
			</div>
			<div style="clear: both;"></div>
		</div>
	<? endforeach; ?>
	<? if($save): ?>
	<div class="line save">
		<p style="text-align: center; margin: 0;"><a href="?<? echo $_SERVER['QUERY_STRING']; ?>&save=y">Save and Secure this Widget</a></p>
	</div>
	<? endif; ?>
 
</body>
 
</html>
